# Лимиты активного времени приложений в минутах за день.
# Формат:
# [Название приложения]: минуты
# [Название 1, Название 2]: общий лимит в минутах для группы
# [*]: общий лимит активного времени всех приложений за день
#
# Название приложения должно совпадать с именем из activity_report.sh.

[Roblox]: 0
[Chrome, Safari]: 60
[Claude]: 0
[*]: 60
